[project]
name = "pydantic-ai-demo"
version = "0.1.0"
description = "Demo files about Pydantic AI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.3",
    "pydantic-ai>=1.9.1",
]

[tool.uv.dev-dependencies]
ruff = ">=0.5.0"
